### PR TITLE
Can now manually specify offset from top

### PR DESCRIPTION
**Pull request by gtmtg**
Before, the AJNotificationView would simply set the offset to the status bar's height (if the view specified is a UIWindow) or 0.0 (if it's not). This could cause undesired behavior if the view is in a UINavigationController (the notification would display below the status bar) or if the view is the `navigationController.view` itself (part of the notification would be cut off by the status bar).

I've changed it so that the user can manually specify the offset. If none is specified, it will default back to the old behavior.

### CODE REVIEW

**Comment by tobinharris** [comment]
Perfect :) 

Can the Podfile be updated?

**Comment by ajerez** [comment]
with that?

**Comment by tobinharris** [comment]
Was meaning - can the Podfile with the latest version of the code be updated. This will mean I can do 

```
pod update
```

For my app, and I'll benefit from the latest fixes.

**Comment by ajerez** [comment]
I don't use Cococapods, so it is not tested, but the tag **0.1** links to the last commit of the repo, and the podfile is linked to this tag, so the update should work.

Sorry for my bad english ;)

**Pull request merged**
